n1 = input('Digite um valor: ')
print('O tipo primitivo desse valor é {}'.format(type(n1)))
print('É Númerico: {}'.format(n1.isnumeric()))
print('É Alfabético: {}'.format(n1.isalpha()))
print('É Alfanumérico: {}'.format(n1.isalnum()))
print('Está em maiúsculas: {}'.format(n1.isupper()))
print('Está em minúsculas: {}'.format(n1.islower()))
print('Está capitalizado: {}'.format(n1.istitle()))
print('É imprimível: {}'.format(n1.isprintable()))
print('É um espaço: {}'.format(n1.isspace()))
print('É decimal: {}'.format(n1.isdecimal()))
print('É um dígito: {}'.format(n1.isdigit()))
print('É um identificador válido: {}'.format(n1.isidentifier()))
print('É ASCII: {}'.format(n1.isascii()))